- `Sequential` - is the class of the sequence of layers in a neural network, we will have only one layer for now, but you can add as many layers as you like and it will be a network consisting of a sequence of layers.

- `Dense` - is a class of fully-connected/linear layer, all neurons are connected to each other.

In [1]:
import numpy as np

X = np.array([[1], [3], [2], [10], [4], [7], [8]])
y = np.array([[4, 12, 8, 40, 16, 28, 32]]).T

In order to train a neural network for any task we need to answer three questions:
1. What is the architecture of the network?
2. What are we optimizing?
3. How are we training?

In [2]:
from keras.layers import Dense
from keras.models import Sequential

model = Sequential([
    Dense(1, input_shape=(1,), activation='linear')
])

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

We have two weights, this is because for each neuron in the linear layer there is a bias. In fact, one neuron in the linear layer is a linear regression

In [3]:
w1, w0 = model.get_weights()
w1, w0

(array([[-0.5196631]], dtype=float32), array([0.], dtype=float32))

In [4]:
X[:1]

array([[1]])

In [5]:
model.predict(X[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([[-0.5196631]], dtype=float32)

In [6]:
w1 * X[:1] + w0

array([[-0.5196631]])

In [7]:
from keras.activations import linear
linear(w1 * X[:1] + w0)

array([[-0.5196631]])

### What to optimize

We have a regression problem, so we will take a loss function for this problem, for example MSE.

In addition, we can also take a metric that we will count and understand whether the network is learning or not.

In [9]:
model.compile(optimizer='sgd', loss='mse', metrics=['mae'])

In [10]:
%%time
model.fit(X, y, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 446ms/step - loss: 709.1211 - mae: 22.5983
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 60.2346 - mae: 6.4567
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 5.2110 - mae: 1.7894
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.5441 - mae: 0.5726
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.1473 - mae: 0.3529
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.1125 - mae: 0.3035
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.1085 - mae: 0.2880
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.1070 - mae: 0.2824
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.1058 - mae: 0.2797
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - loss: 0.1047 - mae: 0.2778
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.1035 - mae: 0.2762
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.1024 - mae: 0.2746
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60

In [11]:
user_1, user_2 = 5, -3
print(f"Testing on new data: {user_1} {user_2}")
print("Neural network prediction: ")
print(model.predict(np.array([[user_1], [user_2]])))

Testing on new data: 5 -3
Neural network prediction: 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
[[ 20.101656]
 [-11.467612]]


In [12]:
nw1, nw0 = model.get_weights()
print('w1 before', w1, 'w1 after', nw1)
print('w0 before', w0, 'w0 after', nw0)

w1 before [[-0.5196631]] w1 after [[3.9461584]]
w0 before [0.] w0 after [0.37086314]


In [13]:
import pandas as pd

pd.DataFrame({
   'True': np.squeeze(y),
   'Pred': np.squeeze(model.predict(X))
})

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


True       Pred
0     4   4.317021
1    12  12.209338
2     8   8.263180
3    40  39.832451
4    16  16.155497
5    28  27.993971
6    32  31.940130